name: Node.js CI

on:
  push:
    branches: [ ci-build-action ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run build
    # - run: npm test
    
    - run: cd dist && git init
    - run: cd dist && git add -A
    - run: cd dist && git commit -m 'deployment'
    - run: cd dist && git push -f git@github.com:s10m/number-bonds-vue-cli.git master:gh-pages
