name: Number bonds game CI

on:
  push:
    branches: [ ci-build-action ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run build
    # - run: npm test
    - name: Configure git credentials
      uses: OleksiyRudenko/gha-git-credentials@v2
    - run: git config --global user.email "actions@github.com"
    - run: git config --global user.name "Github Actions"
    - run: cd dist && git init
    - run: cd dist && git add -A
    - run: cd dist && git commit -m 'deployment'
    - run: cd dist && git push -f https://github.com/s10m/number-bonds-vue-cli.git master:gh-pages
